print ("Julie Anne Lopez")
print ("Pingan Gasan, Marinduque")
print ("July 02, 2004")
print ("College of Information and Computing Sciences")
print ("Bachelor of Science in Information Technology")
print ("2-B")
